runtime: go111

# currently, the server memory footprint is above 512 MB, therefore, it cannot 
# run on the default (F1) config. 
# https://cloud.google.com/appengine/docs/standard/#instance_classes
# It needs a F4_1G
instance_class: F4_1G

# all requests are served by the go runtime (no need for static files)
handlers:
- url: /tkv-client.html
  static_files: tkv-client.html
  upload: tkv-client.html

- url: /9pixels.png
  static_files: 9pixels.png
  upload: 9pixels.png

- url: /
  static_files: tkv-client.html
  upload: tkv-client.html

- url: /css
  static_dir: css
  
- url: /js
  static_dir: js
  
- url: /.*
  script: auto
